### ISSUE TITLE
add option to control text align

### ISSUE THREAD

**Issue by maxzod** [belovance/QuickAlert#11]
![image](https://user-images.githubusercontent.com/47630729/208135248-d643c595-ab10-4c64-8ea1-4b1ff9e98254.png)

at line 102 at  `lib\widgets\quickalert_container.dart`

**Comment by ItsAkashS22** [comment]
Hello @maxzod 👋
Thank You for posting this issue, text alignment matters a lot with respect to languages.
Will be adding the textAlign option to the alert in the upcoming update.
Till Then, Happy Coding 🙌
