### ISSUE TITLE
Close Dialog programatically

### ISSUE THREAD

**Issue by bennito254** [belovance/QuickAlert#13]
Hello, first of all. Thank you for this amazing package. It has helped me provide an elegant and beautiful alerts to my app.

I have faced a situation where I need to close the dialog dynamically, after  certain action. For example, when fetching data from an API is complete, I would want to close the "loading" dialog. I have seen the 'autoCloseDuration' option but there's really no way of knowing how much time such an action would take.

Kindly add the feature to close the dialog after an action. For example:
```
var alert = QuickAlert(options);
if(condition) {
alert.show();
} else {
if(alert.isOpen){
alert.close();
}
}
```

**Comment by kururu-abdo** [comment]
same problem
i want to close alert and start another

**Comment by bennito254** [comment]
I found out that using ```Navigator.of(context, rootNavigator: true).pop();``` closes the dialog. But I believe it would be better if the package had a close method

**Comment by ItsAkashS22** [comment]
Hello @bennito254 & @kururu-abdo 👋
Thank you for using the package and your love towards the package. This enhancement has been already added to the current sprint of feature upgradations. Will be out with an update soon.

I used to handle these type of cases like this:

```dart
QuicklAlert.show(options); // Loading Alert Launched
....
// Do other asynchronous actions
.....
Navigator.pop(context); // Pop out the Loading Alert
```

We can do same thing multiple times before we return a value (if working in a function) or change the state.

Till the new update rolls out, help yourself doing the same or any other workarounds.
Happy Coding ✨

**Comment by bennito254** [comment]
Thank you and Happy Coding

**Comment by oxcakmak** [comment]
> I found out that using `Navigator.of(context, rootNavigator: true).pop();` closes the dialog. But I believe it would be better if the package had a close method

Many thanks, I can also close the message box with this code.

![image_2023-04-16_061325935](https://user-images.githubusercontent.com/48910999/232264243-1c2fc8f3-a38f-4b21-bdcb-32d4196fc05e.png)

**Comment by lucagonzalez** [comment]
> Hello @bennito254 & @kururu-abdo 👋 Thank you for using the package and your love towards the package. This enhancement has been already added to the current sprint of feature upgradations. Will be out with an update soon.
> 
> I used to handle these type of cases like this:
> 
> ```dart
> QuicklAlert.show(options); // Loading Alert Launched
> ....
> // Do other asynchronous actions
> .....
> Navigator.pop(context); // Pop out the Loading Alert
> ```
> 
> We can do same thing multiple times before we return a value (if working in a function) or change the state.
> 
> Till the new update rolls out, help yourself doing the same or any other workarounds. Happy Coding ✨

Hello!

Is this update abandoned?
