### ISSUE TITLE
dark theme support

### ISSUE THREAD

**Issue by trevorwang** [belovance/QuickAlert#17]
**Is your feature request related to a problem? Please describe.**
add dark theme support

**Describe the solution you'd like**
Can use dark theme when application switched to dark mode

**Describe alternatives you've considered**
NONE

**Additional context**
NONE

**Comment by ItsAkashS22** [comment]
Hello @trevorwang 👋🏻 

Please use Color attributes like backgroundColor etc,
With Theme.of(context).<colorAttribute>.

Happy Coding ✨
