### ISSUE TITLE
Set Background Color Feature

### ISSUE THREAD

**Issue by tegaologe** [belovance/QuickAlert#2]
Is there is a feature to change the background color?

**Comment by Almis90** [comment]
Similar question, I would like to set the colors for light and dark mode.

**Comment by ItsAkashS22** [comment]
Hello Developers 👋

Thank you so much for bringing things into notice by writing a issue. With respect and love, the listed enhancement has been done and published.
Options added are as follows:
- Background Color
- Title Color
- Text Color
- Barrier Color

Thank you,
Happy Coding ✨

**Comment by ItsAkashS22** [comment]
Hello Developers 👋

Thank you so much for bringing things into notice by writing a issue. With respect and love, the listed enhancement has been done and published.
Options added are as follows:
- Background Color
- Title Color
- Text Color
- Barrier Color

Thank you,
Happy Coding ✨
