### ISSUE TITLE
Add option to dismiss alert with keyboard "Enter/Cancel" pressed

### ISSUE THREAD

**Issue by matteoberla** [belovance/QuickAlert#27]
Hi, i've noticed that either if the keyboard is opened on the screen or if i'm using an external keyboard (or another input device) or I'm on flutter web, it's not possible to dismiss the alert with a button press from the keyboard.

The solution would be:
- with a single button alert the dismiss will happen when pressing Enter key;
- if the alert has two buttons by pressing Cancel it will do the onCancelBtnTap and with Enter the onConfirmBtnTap.

I think it would be useful as the user hasn't to pass between the keyboard and the tap each time an alert is showed.
Thanks.

**Comment by ItsAkashS22** [comment]
Hello @matteoberla 👋🏻

We have implemented Enter key for confirm actions in alerts. The existing use of the Escape key for dismissing alerts introduces a conflict with using the same for cancel actions, as the Escape key is already widely recognized for dismissal in user interfaces. This standard prevents us from assigning escape key for cancel action without causing confusion. Hence we'll only support keyboard action for confirmation with enter and not support keyboard action for cancel action for now.

Thanks & Happy Coding ✨
