### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Annos** [belovance/QuickAlert#29]
Is there a way to localize the default actions and titles instead of changing them every time from code?
like ( Are you sure ? ) , ( Okay ) , ( Cancel ) ... etc

**Comment by ItsAkashS22** [comment]
### Hello @Annos
_To efficiently localize default actions and titles like "Are you sure?", "Okay", "Cancel", etc., you can leverage Flutter's built-in internationalization (i18n) capabilities. This involves setting up a centralized source for your localized strings and accessing them across your app. And use the same as a parameter to QuickAlert._

**Happy Coding!!!**
