### ISSUE TITLE
Showing dialogs can be easy and better

### ISSUE THREAD

**Issue by topperspal** [belovance/QuickAlert#3]
```dart
QuickAlert.success(context: context);

// or

QuickAlert.success(context); // context as positional parameter

QuickAlert.success(context, message: "File downloaded successfully!");
```
instead of
```dart
QuickAlert.show(
  context: context,
  type: QuickAlertType.success,
);
```

**Comment by ItsAkashS22** [comment]
Hello @topperspal 👋

Yes i could have structured the alert as mentioned above using multiple static functions, but to my perspective and analysis of runtime data, using enum QuickAlertType is a good option, it reduces duplicate lines of code and enables effective reuseability. And many more advantages.

Thank you,
Happy Coding ✨
