### ISSUE TITLE
Option To Set Barrier Color

### ISSUE THREAD

**Issue by thorizer** [belovance/QuickAlert#4]
I want the alert to be non dismissible but still able to see the app in the background, it's too dark especially in a dark mode app
I'm talking about barrierColor: Colors.black.withOpacity(0.5),

**Comment by ItsAkashS22** [comment]
Hello Developers 👋

Thank you so much for bringing things into notice by writing a issue. With respect and love, the listed enhancement has been done and published.
Options added are as follows:
- Background Color
- Title Color
- Text Color
- Barrier Color

Thank you,
Happy Coding ✨
