### ISSUE TITLE
alert stacked without an option to dismiss

### ISSUE THREAD

**Issue by thorizer** [belovance/QuickAlert#5]
this demo will explain it better, when the user try and fail again to reconnect , a new alert pops before dismissing the old one ?  I'm not sure what's happening 
the confirm button doesn't dismiss the alert because it's creating a new alert ?

https://user-images.githubusercontent.com/13587810/187587173-94d878e1-ed95-4728-a5cf-612887960a6d.mp4

**Comment by thorizer** [comment]
actually I think the bug is jut because the confirm button doesn't dismiss the alert

**Comment by ItsAkashS22** [comment]
Hello @thorizer 👋
Lookings like you are triggering the alert multiple times. Debug your code with some conditions to avoid the triggering of alert multiple times and you'll get your expected result.

Thank You,
Happy Coding ⭐

**Comment by thorizer** [comment]
@ItsAkashS22 yes , I know that's why i closed the issue.
I still 50% opacity is too much when i use dark mode

**Comment by ItsAkashS22** [comment]
Hello @thorizer 👋

Yes accepted that and updated the alert with a new option to set barrier color, i hope that helps.

Thank you,
Have Coding ✨
