### ISSUE TITLE
Option to change background colour of Top Part

### ISSUE THREAD

**Issue by rohitsangwan01** [belovance/QuickAlert#6]
Hey nice package ,
like title says , can we change background colour of topCard , right behind the animation part

currently backgroundColor propery changing colour of bottom bart

**Comment by ItsAkashS22** [comment]
Hello @rohitsangwan01, thank you so much for using the package and spending your time to drop this question/feedback here.

Currently the whole Alert Dialog takes a single background color and there is no option to change the color only for the top part, listing your suggestion as a enhancement for the next update and will make sure it solves your issue.

Happy Coding
