### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by JanRegent** [belovance/QuickAlert#7]
Try in expample app

Another exception was thrown: Unable to load asset: packages/quickalert/assets/error.gif
Error while trying to load an asset: Failed to load asset at "assets/assets/error.gif" (404)
Another exception was thrown: Unable to load asset: assets/error.gif
Error while trying to load an asset: Failed to load asset at "assets/assets/confirm.gif" (404)
Another exception was thrown: Unable to load asset: assets/confirm.gif
Error while trying to load an asset: Failed to load asset at "assets/assets/loading.gif" (404)
Another exception was thrown: Unable to load asset: assets/loading.gif
Error while trying to load an asset: Failed to load asset at "assets/assets/loading.gif" (404)
Another exception was thrown: Unable to load asset: assets/loading.gif

**Comment by ItsAkashS22** [comment]
Hello @JanRegent 👋
Looks like you are working on flutter web, after you add the package as a dependency please do restart your application, as the assets will not be mapped to the path on the go. If it doesn't work, please provide more details about your problem with some screenshots if possible.

Happy Coding ✨

**Comment by JanRegent** [comment]
restart your application--> OK

Tanks a lot for Your great work :-)
